name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main


jobs:
  check-application:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

 
    
